#import <Foundation/Foundation.h>

@interface APIurls : NSObject

FOUNDATION_EXPORT NSString *URL_API;
FOUNDATION_EXPORT NSString *const URL_GET_POLLS;
FOUNDATION_EXPORT NSString const *URL_GET_CANDIDATES;
FOUNDATION_EXPORT NSString *URL_SUBMIT_RANKING;
FOUNDATION_EXPORT NSString *URL_SUBMIT_RANKING_POST;
FOUNDATION_EXPORT NSString const *URL_GET_RESULTS;
FOUNDATION_EXPORT NSString const *URL_DUMP_POLL;
FOUNDATION_EXPORT NSString const *URL_RESET_POLL;
FOUNDATION_EXPORT NSString *URL_ADD_POLL;

@end