#import <Foundation/Foundation.h>

@interface Font : NSObject

FOUNDATION_EXPORT NSString* FONT_HOME;
FOUNDATION_EXPORT NSString* FONT_DETTAGLI_POLL;
FOUNDATION_EXPORT NSString* FONT_DETTAGLI_POLL_LIGHT;
FOUNDATION_EXPORT NSString* FONT_DETTAGLI_POLL_BOLD;
FOUNDATION_EXPORT NSString* FONT_CANDIDATES_POLL;
FOUNDATION_EXPORT NSString* FONT_CANDIDATES_POLL_MEDIUM;


@end