#import <Foundation/Foundation.h>

@interface APIurls : NSObject

FOUNDATION_EXPORT NSString *URL_API;
FOUNDATION_EXPORT NSString *URL_GET_POLLS;
FOUNDATION_EXPORT NSString *URL_GET_CANDIDATES;
FOUNDATION_EXPORT NSString *URL_SUBMIT_RANKING;
FOUNDATION_EXPORT NSString *URL_GET_RESULTS;
FOUNDATION_EXPORT NSString *URL_DUMP_POLL;
FOUNDATION_EXPORT NSString *URL_RESET_POLL;
FOUNDATION_EXPORT NSString *URL_ADD_POLL;
FOUNDATION_EXPORT NSString *URL_DELETE_POLL;

@end